ARG OTELCOL_TAG=v0.144.4
FROM signoz/signoz-otel-collector:${OTELCOL_TAG}

ENV SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://clickhouse:9000 \
    SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster \
    SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true \
    SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/signoz-otel-collector migrate bootstrap && /signoz-otel-collector migrate sync up && /signoz-otel-collector migrate async up"]
